name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install QEMU
        run: sudo apt-get install -y qemu-system-x86

      - name: Install bootimage
        run: cargo install bootimage

      - name: Create bootable disk image
        run: cargo bootimage

      - name: Install rust-src component
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
